title: Esther Mang Zing Portofolio
#logo: /assets/img/headshot_circle.png
#description: text below image
description: Educational Consultant @ Solvita A/S | Graduate from Technical University Of Denmark
show_downloads: true
theme: jekyll-theme-minimal
